[package]
name = "duifene-gui"
version.workspace = true
edition.workspace = true

[dependencies]
duifene-core = { path = "../duifene-core" }
slint = { workspace = true }
chrono = { workspace = true }
arboard = { version = "3", default-features = false }

[build-dependencies]
slint-build = "1"

[target.'cfg(windows)'.build-dependencies]
winresource = "0.1"
